package com.employee.system.jdbc;

public class Queries {
	
	public final String INSERT_QUERY="INSERT INTO EMPLOYEE (EMPLOYEE_ID,EMPLOYEE_NAME,EMPLOYEE_ADDRESS,EMPLOYEE_AGE,EMPLOYEE_SALARY,EMPLOYEE_DEPARTMENT) VALUES (?,?,?,?,?,?)";
	
	public final String SELECT_ALL_EMPLOYEES="SELECT * FROM EMPLOYEE";
	
	public final String UPDATE_EMPLOYEE_DETAILS="UPDATE EMPLOYEE SET EMPLOYEE_NAME=?,EMPLOYEE_ADDRESS=?,EMPLOYEE_AGE=?,EMPLOYEE_SALARY=?,EMPLOYEE_DEPARTMENT=? WHERE EMPLOYEE_ID=?";

	public final String DELETE_EMPLOYEE="DELETE FROM EMPLOYEE WHERE EMPLOYEE_ID=?";
}
